version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: ecopass
      POSTGRES_DB: ecocommute
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    env_file:
      - .env
    depends_on:
      - db
      - ml
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "dev"]

  ml:
    build:
      context: ./ml_service
      dockerfile: ../infra/Dockerfile.ml
    env_file:
      - .env
    volumes:
      - ./ml_service:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/Dockerfile.frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev"]

volumes:
  db-data:
